name: "PingFederate"
description: "please login to console first with root:Mimosa2008 and run /etc/pingfederate/bin/run.sh"
version: "8.0.3"
category: "Identiry Federation"
maintainer: 
license: 
projectURL: 
