name: "PingFederate"
description: "(This Image is NOT in use yet!!) このイメージはまだ利用できません！ please login to console first with root:Mimosa2008 and run /etc/pingfederate/bin/run.sh"
version: "7.3"
category: "Identiry Federation"
maintainer: 
license: 
projectURL: 
