Splunk:
  ports:
  - ${public_port}:8000/tcp
  - 1514:1514/tcp
  - 8088:8088/tcp
  - 8089:8089/tcp
  - 8191:8191/tcp
  - 9997:9997/tcp
  environment:
    SPLUNK_BACKUP_DEFAULT_ETC: /var/opt/splunk
    SPLUNK_START_ARGS: --accept-license
    DOCKER_VERSION: 1.9.0
    SPLUNK_BACKUP_APP: /var/opt/splunk/etc/apps
    SPLUNK_GROUP: splunk
    SPLUNK_HOME: /opt/splunk
    SPLUNK_PRODUCT: splunk
    PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    LANG: en_US.utf8
    SPLUNK_USER: root
  log_driver: json-file
  labels:
    io.rancher.container.pull_image: always
    io.rancher.container.start_once: 'true'
    io.rancher.container.volume_cleanup_strategy: none
  entrypoint:
  - /sbin/entrypoint.sh
  command:
  - start-service
  image: splunk/splunk
  volumes:
  - /opt/splunk/etc
  - /opt/splunk/var
  working_dir: /opt/splunk
net: bridge
