.catalog:
  name: "Splunk"
  version: "6.5"
  description: "Test"
  questions:
    - variable: public_port
      description: "Public port to access the Splunk UI"
      label: "UI Access port"
      required: true
      default: "8000"
      type: "int"
