PostgreSQLServer:
  ports:
    - ${postgres_port}:5432
  environment:
        POSTGRES_USER: ${postgres_user}
        POSTGRES_PASSWORD: ${postgres_password}
  labels:
    io.rancher.container.pull_image: always
  tty: true
  image: postgres
  stdin_open: true
