MySQLServer:
  ports:
    - ${public_port}:3306
  environment:
        MYSQL_ROOT_PASSWORD: ${root_password}
        MYSQL_DATABASE: ${db_name}
        MYSQL_USER: ${db_userame}
        MYSQL_PASSWORD: ${db_password}
  labels:
    io.rancher.container.pull_image: always
  tty: true
  image: mysql:5.7
  stdin_open: true
