Graphite:
  scale: 1
.catalog:
    name: "Graphite"
    version: "1.0"
    description: "By default, basic auth is enabled for UI login. user/passwd=guest/guest For the system login, you can use root/root. n\ Also udp receiver is disabled by default. Please login to console and edit /var/graphite/conf/carbon.conf, and modify ENABLE_UDP_LISTENER from False to True"
    questions:
        - variable: ui_port
          description: "Public port to access Graphite Web UI"
          label: "nginx Port"
          required: true
          default: "80"
          type: "int"
        - variable: plainreceiver
          description: "TCP carbon receiver port for plain text data"
          label: "TCP carbon receiver"
          required: true
          default: "2003"
          type: "int"
        - variable: udpplainreceiver
          description: "UDP carbon receiver port for plain text data"
          label: "UDP carbon receiver"
          required: true
          default: "2003"
          type: "int"
        - variable: picklereceiver
          description: "Carbon receiver port for pickle text data (TCP)"
          label: "Pickle carbon receiver"
          required: true
          default: "2004"
          type: "int"

