name: "Graphite"
description: "デフォルトでベーシック認証を有効にしてあります。gues:guest でログインしてください。UIに入った後のログイン画面のクレデンシャルは、 root:root です。"
version: "latest"
category: "Metrics"
maintainer: 
license: 
projectURL: "http://graphite.readthedocs.io/en/latest/index.html"
